apiVersion: v1
kind: Config
clusters:
- cluster:
    server: http://192.168.1.104:8080/events
  name: hit-config
contexts:
- context:
    cluster: hit-config
    user: ""
  name: webhook
current-context: webhook
users: []
preferences: {}